M48
; DRILL file {KiCad 7.0.7} date 2023 September 06, Wednesday 19:49:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-06T19:49:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.190
%
G90
G05
T1
X101.854Y-101.6
T2
X104.394Y-105.664
X106.934Y-105.664
T0
M30
